#! /bin/bash

# BUILD
# Use this file to build any code. 
# Binaries should be copied to $SEC_BIN
# Configuration or additional artifcats should be copied to $SEC_ETC

GO111MODULE=on GOBIN=$SEC_BIN go install github.com/securego/gosec/v2/cmd/gosec@latest
